# Generated by Django 5.2.2 on 2025-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_plate_number_reservation_vehicle_make_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='actual_end_time',
            new_name='last_park_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='actual_start_time',
            new_name='last_park_out',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='floorzone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
