# Generated by Django 5.2.2 on 2025-06-12 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_actual_end_time_reservation_last_park_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglocation',
            name='total_slots',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='slot_number',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
