# Generated by Django 5.2.2 on 2025-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parkingslot_slot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Reserved', 'Reserved'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')], default='Active', max_length=20),
        ),
    ]
