# Generated by Django 5.2.2 on 2025-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglocation',
            name='slots',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
