# Generated by Django 5.2.2 on 2025-06-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parkinglocation_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Reserved', 'Reserved'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
