# Generated by Django 5.2.2 on 2025-06-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reservation_receipt_image_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='receipt_image',
            new_name='receipt',
        ),
    ]
