# Generated by Django 5.2.2 on 2025-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_receipt_image_reservation_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Reserved', 'Reserved'), ('Overdue', 'Overdue'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
