# Generated by Django 5.2.2 on 2025-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
