# Generated by Django 5.2.2 on 2025-06-16 00:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parkingslot_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Reserved', 'Reserved'), ('Active', 'Active'), ('Overdue', 'Overdue'), ('Checked-out', 'Checked-out'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
